export const hotelTypes = [
  "Budget",
  "Luxury",
  "Boutique",
  "Resort",
  "Business",
  "Airport",
  "Hostel",
  "Motel",
  "Villa",
  "Apartment",
  "Guest House",
  "Bed and Breakfast",
  "Capsule",
  "Eco",
  "Casino",
  "All-Inclusive",
  "Extended Stay",
  "Heritage",
  "Serviced Apartment",
  "Beachfront",
  "Mountain Retreat",
  "Spa Hotel",
  "Golf Resort",
  "Farm Stay",
  "Chalet",
  "Treehouse",
  "Cottage",
  "Riad",
  "Ryokan",
  "Pension",
  "Inns",
  "Homestay",
  "Floating Hotel",
  "Ice Hotel",
  "Cave Hotel",
  "Safari Lodge",
  "Wine Hotel",
  "Glamping",
  "Love Hotel",
  "Timeshare"
];


export const hotelFacilities = [
  "Free WiFi",
  "Swimming Pool",
  "Spa",
  "Gym/Fitness Center",
  "Restaurant",
  "Bar",
  "Room Service",
  "24-Hour Front Desk",
  "Airport Shuttle",
  "Air Conditioning",
  "Parking",
  "Pet Friendly",
  "Laundry Service",
  "Non-smoking Rooms",
  "Business Center",
  "Concierge Service",
  "Wheelchair Accessible",
  "Breakfast Included",
  "Beach Access",
  "Balcony with View"
];
